test_framework:
  name: "HXP-Enterprise-LLM-Test-Framework"
  version: "1.0.0"
  environment: "development"
  
  structure:
    component_tests: true
    integration_tests: true
    service_tests: true
    utilities: true
  
  coverage:
    minimum_line_coverage: 95
    minimum_branch_coverage: 90
    minimum_function_coverage: 95
    coverage_report_format: "html"
  
  performance:
    latency_threshold_ms: 2000
    throughput_threshold_rps: 50
    memory_limit_gb: 90
    cpu_limit_cores: 8
    performance_timeout_seconds: 300
  
  security:
    vulnerability_threshold: 0
    security_test_coverage: 100
    compliance_score: 100
    security_scan_enabled: true
  
  certification:
    component_level: true
    integration_level: true
    service_level: true
    system_level: true
  
  reporting:
    output_format: "html"
    output_directory: "/opt/citadel/reports/testing"
    include_coverage: true
    include_performance: true
    include_security: true 