# DeepSeek-R1-32B Optimization Configuration
model: "deepseek-r1:32b"
role: "strategic_research_intelligence"

optimization:
  temperature: 0.6
  top_p: 0.9
  max_tokens: 4096
  context_length: 131072
  
enterprise_settings:
  strategic_research: true
  competitive_intelligence: true
  market_analysis: true
  strategic_planning: true
  research_depth: "comprehensive"
  
business_applications:
  competitive_analysis: true
  market_research: true
  strategic_consulting: true
  investment_analysis: true
  industry_intelligence: true
  
performance:
  target_response_time: 90
  memory_allocation: "40GB"
  concurrent_requests: 2
  baseline_performance: "1m25s-1m42s"
  
use_cases:
  - competitive_landscape_analysis
  - market_research_reports
  - strategic_planning_frameworks
  - investment_due_diligence
  - industry_trend_analysis
  - business_opportunity_assessment

# Performance Metrics from Testing
baseline_tests:
  competitive_analysis: "✅ 1m42s - 7.5KB comprehensive analysis"
  market_research: "✅ 1m35s - 9.1KB detailed SME adoption trends"
  strategic_planning: "✅ 1m25s - 8.6KB European market framework"
  consultation_scenario: "✅ 1m39s - 8.3KB Series C funding analysis"
  
system_resources:
  model_size: "19GB"
  architecture: "qwen2"
  parameters: "32.8B"
  context_length: "131072"
  quantization: "Q4_K_M"
  memory_requirement: "High"
  processing_intensity: "Strategic depth focused"
  
validation_status: "✅ OPTIMIZED"
optimization_date: "2025-07-25"
