# FastAPI Gateway Middleware Configuration
middleware:
  cors:
    enabled: true
    allow_origins: "*" # Should be restricted in production, see global security.yaml
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]
  logging:
    enabled: true # Set to true to enable detailed request/response logging
    level: "info" # debug, info, warning, error
    include_body: false # Set to true to include request body (use with caution for large requests/secrets)
  metrics:
    enabled: false # To be implemented later with Prometheus
